{% set name = "pytups" %}
{% set version = "0.88.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1f96fe41337ee65250e71f973fe3b91495a55dab42feebc0ff66ae00af1004a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pytups
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pchtsp/pytups
  summary: 'data wrangling for lists of tuples and dictionaries'
  description: |
    I grew used to the chained operations in R’s tidyverse packages or, although not a great
    fan myself, python’s pandas. I find myself using dictionary and list comprehensions all 
    the time to pass from one data format to the other efficiently. But after doing it for the 
    Nth time, I thought of automating it.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://pchtsp.github.io/pytups/
  dev_url: https://github.com/pchtsp/pytups

extra:
  recipe-maintainers:
    - pchtsp
