{% set name = "pytups" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a04133724ee6218d272f7473573d041c88bc7266f86db3ec7705c0ee2757ace

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pytups
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pchtsp/pytups
  summary: 'data wrangling for lists of tuples and dictionaries'
  description: |
    I grew used to the chained operations in R’s tidyverse packages or, although not a great
    fan myself, python’s pandas. I find myself using dictionary and list comprehensions all 
    the time to pass from one data format to the other efficiently. But after doing it for the 
    Nth time, I thought of automating it.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://pchtsp.github.io/pytups/
  dev_url: https://github.com/pchtsp/pytups

extra:
  recipe-maintainers:
    - pchtsp
